name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyserial
      - name: Build exe with PyInstaller
        run: |
          pyinstaller --onefile --windowed rfid_reader.py --name rfid_reader --hidden-import=pyserial.tools.list_ports_windows --hidden-import=pyserial.tools.list_ports_common --hidden-import=pyserial.tools.list_ports_posix --hidden-import=pyserial.tools.list_ports_osx --hidden-import=pyserial.tools
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rfid_reader_windows_exe
          path: dist/rfid_reader.exe
